version: '3.6'
services:
  mongo:
   image: mongo:4.2.0
   ports:
      - "27017:27017"
  web:
   image: ramkipanni/examplerestimage:latest
   ports:
      - "9090:8080"
   environment:
      spring.data.mongodb.host: mongo
